### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MarcoMaz** [MarcoMaz/basic-metronome-react-hooks#1]
- [ ] fix const
- [x] write Stack Overflow about the delay
- [x] have a live version
- [x] Add SCSS
- [x] Implement Material Design
- [ ] Style it
  - [ ] Add Number of Beats 
- [ ] fix README

**If there's time left**
- [ ] add Volume option
